### ISSUE TITLE
Error message on installation of the package

### ISSUE THREAD

**Issue by bernard-osei** [mrc-ide/drjacoby#123]
Hi there, please  i am trying to install the drjacoby package, however, i am faced with the error message below: Error: Failed to install 'drjacoby' from GitHub:
  cannot open the connection
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers

Please, i would appreciate any assistance given? Thank you.

**Comment by bobverity** [comment]
Hi Bernard,

Thanks for your message. It's a bit tricky to diagnose what exactly went wrong there, when I search I find that it may be caused by an interrupted connection or other issue unpacking the tarball.

The easiest solution may be to install via another method. We are currently working on getting drjacoby up on the runiverse, which would provide a simpler installation process. This should hopefully be up and running in the next few days, so I'll come back to you then. In the meantime, let me know if you make any further progress with installing the usual way.

**Comment by bobverity** [comment]
Hi Bernard,
We have the R-universe installation method running now, so you could try this as an alternative:

install.packages('drjacoby', repos = 'https://mrc-ide.r-universe.dev')

**Comment by bernard-osei** [comment]
Alright, Thank you. I will try again to install.
*Bernard Osei*
*PhD (Mathematics), ACoMVec/University of Cape Coast*

*MSc Mathematical Science*
*Africa Institute for Mathematical Sciences, Ghana*
*Summerhill Estates| East Legon Hills| Santoe| Accra*
P.O. Box LG DTD 20046, Legon, Accra | *GPS: GK- 0647-1372*
*Mobile: +23326396616**4/+233557079524*
*ORCID ID: *https://orcid.org/0000-0002-2534-5051

**Comment by bernard-osei** [comment]
Hi, thank you; it worked now.
*Bernard Osei*
*PhD (Mathematics), ACoMVec/University of Cape Coast*

*MSc Mathematical Science*
*Africa Institute for Mathematical Sciences, Ghana*
*Summerhill Estates| East Legon Hills| Santoe| Accra*
P.O. Box LG DTD 20046, Legon, Accra | *GPS: GK- 0647-1372*
*Mobile: +23326396616**4/+233557079524*
*ORCID ID: *https://orcid.org/0000-0002-2534-5051

**Comment by bobverity** [comment]
Fantastic! Glad to know the R-universe method had made things easier 😊

Best wishes,

Bob Verity
Lecturer in Genomic Epidemiology and Modelling
Imperial College London

----------------------------------------------------------------
I work flexibly and may send emails outside normal working hours. I do not expect an immediate response


From: Bernard Osei ***@***.***>
Date: Wednesday, 26 June 2024 at 09:29
To: mrc-ide/drjacoby ***@***.***>
Cc: Verity, Robert J ***@***.***>, Comment ***@***.***>
Subject: Re: [mrc-ide/drjacoby] Error message on installation of the package (Issue #123)
Hi, thank you; it worked now.
*Bernard Osei*
*PhD (Mathematics), ACoMVec/University of Cape Coast*

*MSc Mathematical Science*
*Africa Institute for Mathematical Sciences, Ghana*
*Summerhill Estates| East Legon Hills| Santoe| Accra*
P.O. Box LG DTD 20046, Legon, Accra | *GPS: GK- 0647-1372*
*Mobile: +23326396616**4/+233557079524*
*ORCID ID: *https://orcid.org/0000-0002-2534-5051
