### ISSUE TITLE
Initial parameters argument

### ISSUE THREAD

**Issue by pwinskill** [mrc-ide/drjacoby#13]
Separate initial parameters argument, removing from df_params.
Optional - not needed if stating values can be drawn from min & max. Warning that it is needed if either of min or max  = Inf
Input is a list, whcih can contain a vector for each chain of a parameter

**Comment by pwinskill** [comment]
Tibbles make list columns easy nad the init params could be a list column.

On this same topic. I remember us discussing a more intiuitive input format for `df_params`. A tibble can be entered rowwise, which may be an option (although additional dependency):
```
tribble(
  ~x, ~y,  ~z,
  "a", 2,  3.6,
  "b", 1,  8.5
)
#> # A tibble: 2 x 3
#>   x         y     z
#>   <chr> <dbl> <dbl>
#> 1 a         2   3.6
#> 2 b         1   8.5
```

**Comment by bobverity** [comment]
Solved with define_params() function. Using dataframe instead of tibble
