### ISSUE TITLE
plot_par show argument not specific

### ISSUE THREAD

**Issue by bobverity** [mrc-ide/drjacoby#15]
When running plot_par() with, for example, show = "eta", it will also show all parameters containing this string, for example "beta" and "zeta". Need to make show argument completely specific.

**Comment by pwinskill** [comment]
Had done this intentionally @bobverity , (was dealing with pars: sigma1 sigma2 sigma3 ... mu, eta and wanted to just get rid of al the sigmas.)

Happy to make specific if you think an easier use case - not sure if there is a nicer (more standard) regex-y way to deal with this issue -I'll have a check
