### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by pwinskill** [mrc-ide/drjacoby#17]
Does the txtProgressBar lead to behaviour of jumping in and out of R from Rcpp @bobverity ?

**Comment by bobverity** [comment]
Yep, it will do. If we're using it within the MCMC we should only update every so often. Really a maximum of every 1% progress, probably less in practice.

**Comment by bobverity** [comment]
Checked and is currently being updated every 1% increment only, which should not cause very large overhead.
