### ISSUE TITLE
problem installing drjacoby

### ISSUE THREAD

**Issue by gracia509** [mrc-ide/drjacoby#35]
Dear Dr Verity,

I have a problem to install the drjacoby.  
Message is as below.
package ‘testthat’ successfully unpacked and MD5 sums checked
Error: Failed to install 'drjacoby' from GitHub:
  Failed to install 'ggisoband' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘testthat’

Thank you.

**Comment by pwinskill** [comment]
The depedency on package ggisoband has been removed from version1.0 as it is no longer used. This should hopefulyl solve this installation issue.

**Comment by pwinskill** [comment]
...and also merged into master which should also solve the issue for default `install_github()`

**Comment by gracia509** [comment]
installed and thank you

**Comment by bobverity** [comment]
Great, glad it's working now.
Just to be safe I would make sure you change your install instruction to `devtools::install_github("mrc-ide/drjacoby", ref = "version1.0")`, rather than installing off master. We might update to version1.1 some time soon, which will not be backwards-compatible.
